### ISSUE TITLE
Please upgrade to latest re2c

### ISSUE THREAD

**Issue by vinipsmaker** [nunoplopes/chocore2c#1]
I just need re2c 2.1, but we're already at version 3.0.

**Comment by NickStrupat** [comment]
Good timing, I just came here to ask the same. I was hoping to find a build script for `re2c` for Windows in this repo.

@nunoplopes, would it be possible for you to commit your build configuration?

**Comment by nunoplopes** [comment]
This is what I used to compile re2c 2.1: https://github.com/nunoplopes/chocore2c/blob/master/tools/VERIFICATION.txt
I believe more recent versions are easier to compile.

I'll try to get to this next weekend or so.

**Comment by nunoplopes** [comment]
submitted: https://community.chocolatey.org/packages/re2c/3.0
It usually takes a few days to be available for everyone.
